name: 'Terraform Destroy'

on:
  workflow_dispatch:  

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2

      - name: 'Terraform Init'
        run: |
          cd terraform-test
          terraform init

      - name: 'Terraform Plan Destroy'
        run: |
          cd terraform-test
          EMAIL="${{ secrets.AUTHORIZED_USER }}"
          
          terraform plan -destroy \
            -var="support_email=${{ secrets.SUPPORT_EMAIL }}" \
            -var="iap_authorized_users=[\"user:${EMAIL}\"]" \
            -var="github_repo=${{ github.repository }}" \
            -var="user_email=${{ secrets.AUTHORIZED_USER }}"

      - name: 'Terraform Destroy'
        run: |
          cd terraform-test
          EMAIL="${{ secrets.AUTHORIZED_USER }}"
          
          terraform destroy -auto-approve \
            -var="support_email=${{ secrets.SUPPORT_EMAIL }}" \
            -var="iap_authorized_users=[\"user:${EMAIL}\"]" \
            -var="github_repo=${{ github.repository }}" \
            -var="user_email=${{ secrets.AUTHORIZED_USER }}" 